config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :todos 

  root "todos#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
	belongs_to :user

	validates :body, numericality: { greater_than: 1, less_than: 5000, 
	message: "Yo, your message is wrong" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :todos
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index

    @todos = current_user.todos
  end

  def show
    @user = current_user
    @todos = @user.todos.find(params[:id])
  end

  def new
    @todo = current_user.todos.new
  end

  def create
    user = User.find(current_user.id)
    user.todos.create(todo_params)

    redirect_to todos_path

  end

  def edit
    @user = User.find(current_user.id)
    @todo = @user.todos.find(params[:id])
  end

  def update
    user = User.find(current_user.id)
    todo = user.todos.find(params[:id])
    todo.update(todo_params)

    redirect_to todos_path
  end

  def destroy
    user = User.find(current_user.id)
    user.todos.destroy(params[:id])
    redirect_to todos_path

  end

  protected
  def todo_params
    params.require(:todo).permit(:title, :body, :priority, :complete)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>

    <link rel="stylesheet" type="text/css" href="css/stylee.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="javaScripts/main.js" type="text/javascript"></script>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    	<p class="navbar-text pull-right">
  		<% if user_signed_in? %>
  		  Logged in as <strong><%= current_user.email %></strong>.
  		  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  		  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>

  		<% else %>
  		  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  		  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  		<% end %>

  	</p>

    <div class="heading-links">
      <ul>
        <li class="new-todo-link"><a href="http://localhost:3000/todos">Home</a></li>
        <li class="new-todo-link"><%= link_to "New todo", new_todo_path %></li>
      </ul>
    </div>

  </header>

	<% if notice %>
  		<p class="alert alert-success"><%= notice %></p>
  	<% end %>

  	<% if alert %>
  		<p class="alert alert-danger"><%= alert %></p>
  	<% end %>

    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<div class="page-container">
	<%= form_for(@todo) do |f| %>

	  <%= f.label :title %>
	  <%= f.text_field :title %>

	  <%= f.label :body %>
	  <%= f.text_field :body %>

	  <%= f.label :priority %>
	  <%= f.text_field :priority %>

	  <%= f.label :complete %>
	  <%= f.text_field :complete %>

	  <%= f.submit %>

	<% end %>
</div>

app/views/todos/_todo.html.erb
<div class="todo">
  <p>Title: <strong><%= todo.title %></strong></p>
  <p>body: <strong><%= todo.body %></strong></p>
  <p class="priority-text">Priority: <strong><%= todo.priority %></strong></p>
  <p class="complete-text">Complete: <strong><%= todo.complete %></strong></p>

  <br>
  <footer>
	  <%= link_to "Show Page", todo if action_name == "index" %> |
	  <%= link_to "Edit Page", edit_todo_path(todo) %>
  </footer>
</div>
<div class="sep"></div>

app/views/todos/edit.html.erb
<%= render "form" %>

app/views/todos/index.html.erb
<div class="todos-main-container">
	<%= render @todos %>
</div>

app/views/todos/new.html.erb
<%= render 'form' %>

app/views/todos/show.html.erb
<div class="page-container">
	  <%= render @todos %>

	  <div id="delete-link">
	  <%= link_to "Delete", @todo, method: :delete, data: { confirm: "Are you sure?" } %>
	  </div>
	<br>

	

</div>